### ISSUE TITLE
Add support for node 24

### ISSUE THREAD

**Issue by Laurin-W** [inrupt/solid-client-authn-js#4025]
Title is self-explanatory.

Currently supported versions: node 20, node 22

**Comment by rubensworks** [comment]
> And @srosset81 I don't really agree: the supported engines field is indicative, it doesn't prevent downstream consumers from running in an environment that isn't explicitly supported. 

@NSeydoux Unfortunately, some package managers (such as yarn classic, which is still quite popular, we also use it for Comunica) error on unsupported engine versions by default, and only warn when using the `--ignore-engines` flag.
Our Comunica Link Traversal users run into this problem all the time (as we depend on solid-client-authn-js), so not having the engines field would make our lives a lot easier.

**Comment by jeswr** [comment]
Hi @NSeydoux 👋 

Could you cut a release with the changes in #4141 - thankyou!

**Comment by NSeydoux** [comment]
Hi @jeswr , sorry for the late notification (and slow reaction), but v4.0.0 should fix the issue.

**Comment by rubensworks** [comment]
@NSeydoux FYI, Node 26 is already out in the meantime. So the problem we had before still persists.

I would strongly recommend removing the "engines" entry.
